### ISSUE TITLE
Load Errors

### ISSUE THREAD

**Issue by CJRobertson** [smallfritspoo/SpaceOregonTrail#7]
<img width="1507" alt="ErrorsToAddress" src="https://user-images.githubusercontent.com/13307644/55392178-a265ac80-54ef-11e9-99fc-7a6d0506a482.PNG">

**Comment by smallfritspoo** [comment]
See PR #8 but tl;dr InventorySlot class was never setup or referenced so the calls to a per instance use of the class was not available. Removal of this file is the requirement, verified no references in scene.
